name: Basic TestCafe Workflow
on: [push]

jobs:
  build:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - name: Install TestCafe
        uses: DevExpress/testcafe-action@latest
        with:
          args: '-v'
      - name: Run custom runner
        run: node runner.js
